{ pkgs, ... }:

{
  home.packages = with pkgs; [
    neovim
    lazygit # backs lua/plugins/git.lua's <leader>gg
  ];

  # Symlinks the repo's init.lua/lua tree straight into ~/.config/nvim,
  # so editing "the real config" and editing this repo are the same
  # files. lazy-lock.json (exact plugin commit pins) isn't here yet -
  # it's generated by lazy.nvim on first launch; see docs/GUIDE.md for
  # the one-time step to bring it under version control too.
  xdg.configFile."nvim/init.lua".source = ./init.lua;
  xdg.configFile."nvim/lua" = {
    source = ./lua;
    recursive = true;
  };
}
